### ISSUE TITLE
changefreq and priority

### ISSUE THREAD

**Issue by rwwagner90** [wackerservices/SitemapAutogenerator#3]
Hi, thanks for the addon! I see changefreq and priority are currently set to daily and 0.8. I'm not super familiar with how sitemaps work, but is it a good idea to hardcode them like that? https://github.com/wackerservices/SitemapAutogenerator/blob/master/blueprints/sitemap-autogenerator/index.js#L131

**Comment by rupdegraff** [comment]
There is no way to currently assign custom <priority> values for specific routes or to specify custom <changefreq> values.  It would be great to add those features.

**Comment by rupdegraff** [comment]
`changefreq` and `priority` can both be customized as of sitemap-autogenerator 1.0.  Please see the new README for instructions on how to set these values.
